# Generated by Django 3.0.5 on 2020-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalbooks',
            name='weight',
            field=models.FloatField(),
        ),
    ]
