# Generated by Django 3.1 on 2020-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200511_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbooks',
            name='aladinPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='totalbooks',
            name='kyoboPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='totalbooks',
            name='naverPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='totalbooks',
            name='ridibooksPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='totalbooks',
            name='yes24Price',
            field=models.IntegerField(default=0),
        ),
    ]
