# Generated by Django 3.1 on 2020-08-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_totalbooks_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbooks',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='totalbooks',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
