# Generated by Django 3.1 on 2020-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200819_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalbooks',
            old_name='link',
            new_name='aladinLink',
        ),
        migrations.AddField(
            model_name='totalbooks',
            name='kyoboLink',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='totalbooks',
            name='naverLink',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='totalbooks',
            name='ridibooksLink',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='totalbooks',
            name='yes24Link',
            field=models.URLField(default=''),
        ),
    ]
