# Generated by Django 3.1 on 2020-09-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200819_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookstore', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
    ]
