# Generated by Django 3.1 on 2020-09-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
