# Generated by Django 3.1 on 2020-09-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20200906_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aladin',
        ),
        migrations.DeleteModel(
            name='Kyobo',
        ),
        migrations.DeleteModel(
            name='Naver',
        ),
        migrations.DeleteModel(
            name='Ridibooks',
        ),
        migrations.DeleteModel(
            name='Yes24',
        ),
    ]
